version: "3.9"
services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - "8092:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/